"""
Base Strategy Class.

All trading strategies inherit from this abstract base class.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Literal, Optional

import pandas as pd


@dataclass
class StrategySignal:
    """Signal generated by a strategy."""
    decision: Literal["LONG", "SHORT", "FLAT"]
    confidence: float
    reason: str
    strategy_name: str
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    indicators: Dict[str, float] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.now)

    def to_dict(self) -> Dict:
        return {
            "decision": self.decision,
            "confidence": round(self.confidence, 4),
            "reason": self.reason,
            "strategy_name": self.strategy_name,
            "entry_price": round(self.entry_price, 4) if self.entry_price else None,
            "stop_loss": round(self.stop_loss, 4) if self.stop_loss else None,
            "take_profit": round(self.take_profit, 4) if self.take_profit else None,
            "indicators": {k: round(v, 4) for k, v in self.indicators.items()},
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class StrategyConfig:
    """Base configuration for strategies."""
    symbol: str = "BTC/USDT"
    timeframe: str = "1h"
    risk_per_trade_pct: float = 0.5
    stop_loss_pct: float = 0.02
    take_profit_pct: float = 0.04
    min_confidence: float = 0.4


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    Subclasses must implement:
    - name property
    - description property
    - generate_signal method
    - get_required_indicators method
    """

    def __init__(self, config: Optional[StrategyConfig] = None):
        self.config = config or StrategyConfig()
        self._last_signal: Optional[StrategySignal] = None

    @property
    @abstractmethod
    def name(self) -> str:
        """Strategy name."""
        pass

    @property
    @abstractmethod
    def description(self) -> str:
        """Brief description of the strategy."""
        pass

    @property
    def suitable_regimes(self) -> List[str]:
        """
        Market regimes this strategy works best in.
        Override in subclass for specific regimes.
        """
        return ["all"]

    @abstractmethod
    def generate_signal(self, ohlcv: pd.DataFrame) -> StrategySignal:
        """
        Generate a trading signal from OHLCV data.

        Args:
            ohlcv: DataFrame with columns [open, high, low, close, volume]

        Returns:
            StrategySignal with decision, confidence, and supporting data
        """
        pass

    @abstractmethod
    def get_required_indicators(self) -> List[str]:
        """Return list of indicator names this strategy uses."""
        pass

    def add_indicators(self, ohlcv: pd.DataFrame) -> pd.DataFrame:
        """Add required indicators to the dataframe."""
        return ohlcv.copy()

    def calculate_position_size(
        self,
        balance: float,
        entry_price: float,
        stop_loss_price: float,
    ) -> float:
        """
        Calculate position size based on risk management.

        Args:
            balance: Current account balance
            entry_price: Planned entry price
            stop_loss_price: Stop loss price

        Returns:
            Position size in base currency units
        """
        risk_amount = balance * (self.config.risk_per_trade_pct / 100)
        risk_per_unit = abs(entry_price - stop_loss_price)

        if risk_per_unit <= 0:
            return 0.0

        return risk_amount / risk_per_unit

    def _flat_signal(self, reason: str = "No clear signal") -> StrategySignal:
        """Helper to create a FLAT signal."""
        return StrategySignal(
            decision="FLAT",
            confidence=0.0,
            reason=reason,
            strategy_name=self.name,
        )
